# Type Name          ID GECOS                          Home                       Shell
u      swift-vapor   -  "Swift Vapor runtime account" /nonexistent               /usr/sbin/nologin
u      swift-deploy  -  "Swift Vapor deploy account"  /var/lib/swift-deploy       /bin/bash
