# Type Name                ID GECOS                                Home         Shell
g      swift-backup-check  -  -
u!     swift-backup        -  "Swift Vapor encrypted backup job" /nonexistent /usr/sbin/nologin
m      swift-backup        swift-backup-check
m      swift-deploy        swift-backup-check
