import Fluent
import Foundation
import Vapor

enum ExportJobFormat: String, Codable, CaseIterable, Sendable {
    case json
    case graphml
    case markdown
    case html
    case pdf
}

enum ExportJobStatus: String, Codable, CaseIterable, Sendable {
    case pending
    case processing
    case completed
    case failed
    case cancelled

    var isTerminal: Bool {
        self == .completed || self == .failed || self == .cancelled
    }
}

struct ExportJobManifest: Content, Equatable, Sendable {
    let schemaVersion: Int
    let jobID: UUID
    let scanID: UUID
    let format: ExportJobFormat
    let sourceStatus: String
    let sourceCreatedAt: Date?
    let sourceCompletedAt: Date?
    let generatedAt: Date
    let resultCount: Int
    let resultSetSHA256: String
    let artifactSHA256: String
    let artifactBytes: Int
    let contentType: String
    let filename: String
    let complete: Bool
}

/// Owner-scoped, durable export request. The generated bytes and their manifest
/// are independently authenticated and encrypted so a database-only compromise
/// reveals queue metadata, not harvested OSINT content or target-derived names.
final class ExportJob: Model {
    static let schema = "export_jobs"

    @ID(key: .id) var id: UUID?
    @Parent(key: "user_id") var user: User
    @Parent(key: "scan_id") var scan: Scan
    @Field(key: "format") var formatRaw: String
    @Field(key: "status") var statusRaw: String
    @Field(key: "progress_completed") var progressCompleted: Int
    @Field(key: "progress_total") var progressTotal: Int
    @OptionalField(key: "artifact") var artifactCipher: String?
    @OptionalField(key: "manifest") var manifestCipher: String?
    @OptionalField(key: "failure_code") var failureCode: String?
    @Field(key: "cancel_requested") var cancelRequested: Bool
    @Field(key: "attempt_count") var attemptCount: Int
    @Field(key: "max_attempts") var maxAttempts: Int
    @OptionalField(key: "lease_owner") var leaseOwner: String?
    @OptionalField(key: "lease_expires_at") var leaseExpiresAt: Date?
    @Timestamp(key: "created_at", on: .create) var createdAt: Date?
    @Timestamp(key: "updated_at", on: .update) var updatedAt: Date?
    @OptionalField(key: "started_at") var startedAt: Date?
    @OptionalField(key: "completed_at") var completedAt: Date?
    @Field(key: "expires_at") var expiresAt: Date

    init() {}

    init(
        id: UUID = UUID(),
        userID: UUID,
        scanID: UUID,
        format: ExportJobFormat,
        maxAttempts: Int,
        expiresAt: Date
    ) {
        self.id = id
        self.$user.id = userID
        self.$scan.id = scanID
        self.formatRaw = format.rawValue
        self.statusRaw = ExportJobStatus.pending.rawValue
        self.progressCompleted = 0
        self.progressTotal = 0
        self.cancelRequested = false
        self.attemptCount = 0
        self.maxAttempts = maxAttempts
        self.expiresAt = expiresAt
    }

    var format: ExportJobFormat? { ExportJobFormat(rawValue: formatRaw) }
    var status: ExportJobStatus? { ExportJobStatus(rawValue: statusRaw) }

    var artifactData: Data? {
        get throws {
            guard let artifactCipher else { return nil }
            let encoded = try FieldCrypto.decryptStored(
                artifactCipher,
                field: .exportArtifact,
                recordID: id
            )
            guard let data = Data(base64Encoded: encoded) else {
                throw DecodingError.dataCorrupted(
                    .init(codingPath: [], debugDescription: "Export artifact is not valid base64.")
                )
            }
            return data
        }
    }

    var manifest: ExportJobManifest? {
        get throws {
            guard let manifestCipher else { return nil }
            let encoded = try FieldCrypto.decryptStored(
                manifestCipher,
                field: .exportManifest,
                recordID: id
            )
            guard let data = encoded.data(using: .utf8) else {
                throw DecodingError.dataCorrupted(
                    .init(codingPath: [], debugDescription: "Export manifest is not UTF-8.")
                )
            }
            return try JSONDecoder().decode(ExportJobManifest.self, from: data)
        }
    }

    func setArtifact(_ data: Data, manifest: ExportJobManifest) throws {
        guard let id else { preconditionFailure("ExportJob must have an ID before encryption") }
        artifactCipher = FieldCrypto.encrypt(
            data.base64EncodedString(),
            field: .exportArtifact,
            recordID: id
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        manifestCipher = FieldCrypto.encrypt(
            String(decoding: try encoder.encode(manifest), as: UTF8.self),
            field: .exportManifest,
            recordID: id
        )
    }
}
