# Type Path                                 Mode User         Group        Age Argument
d      /var/lib/swift-deploy                0755 root         root         -   -
d      /var/lib/swift-deploy/.ssh           0755 root         root         -   -
d      /var/lib/swift-deploy/repository     0700 swift-deploy swift-deploy -   -
d      /srv/swift-vapor                     0755 swift-deploy swift-deploy -   -
d      /srv/swift-vapor/releases            0755 swift-deploy swift-deploy -   -
